services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dc
      POSTGRES_USER: dc
      POSTGRES_PASSWORD: dc
    ports:
      - "5432:5432"
    volumes:
      - './postgres_data:/var/lib/postgresql/data'